INSERT INTO PCDM.DW_FACT_PREMIUM_TRANSACTION (
ORG_ID,
PRODUCT_ID,
POLICY_ID,
LOC_ID,
COVG_ID,
AGENT_ID,
AGENCY_ID,
PRIM_NAMED_INSURED_ID,
ACCT_ID,
DATE_ID,
--MONTH_ID,
ALT_PREMIUM_TRANSACTION_ID,
REC_TYPE_ID,
ACCTG_PRD_ID,
TRANSACTION_PROC_DT_ID,
TRANSACTION_EFF_DT_ID,
TRANSACTION_EXP_DT_ID,
TRANSACTION_PROC_DATETIMESTAMP,
RISK_TYPE_CD,
SOURCE,
TRANSACTION_TYPE_CD,
TRANSACTION_CD,
TRANSACTION_SEQ,
CURRENCY_CD,
TRANSACTION_AMOUNT,
TRANSACTION_ALLOC_CD,
WRITTEN_PREMIUM_AMOUNT,
INFORCE_PREMIUM_AMOUNT,
TAX_AMOUNT,
FEE_AMOUNT,
SURCHARGE_AMOUNT,
COMMISSION_AMOUNT,
COMMISSION_PERCENT,
PREMIUM_FULLY_EARNED_FLAG,
ESTIMATED_PREMIUM_AMOUNT,
REPORTED_PREMIUM_AMOUNT,
AUDIT_PREMIUM_AMOUNT,
PREMIUM_BASIS_AMOUNT,
AUDITABLE_FLAG,
ETL_ACTIVE_FLAG,
ETL_ADD_DATETIMESTAMP,
ETL_LAST_UPDATE_DATETIMESTAMP,
TOTALPREMIUMRPT,
TOTALREPORTEDPREMIUM,
POLICY_STATUS_DESC_EXT	
)  
SELECT
 PCDM.DW_DIM_ORGANIZATION.ORG_ID AS ORG_ID,
 PCDM.DW_DIM_PRODUCT.PRODUCT_ID AS PRODUCT_ID,
 PCDM.DW_DIM_POLICY.POLICY_ID AS POLICY_ID,
 PCDM.DW_DIM_LOCATION.LOCATION_ID AS LOC_ID,
 PCDM.DW_DIM_COVERAGE.COVERAGE_ID AS COVG_ID,
 PCDM.DW_DIM_AGENT.AGENT_ID AS AGENT_ID, 
 PCDM.DW_DIM_AGENCY.AGENCY_ID AS AGENCY_ID,
 PCDM.DW_DIM_NAMED_INSURED.NAMED_INSURED_ID AS PRIM_NAMED_INSURED_ID,
 PCDM.DW_DIM_ACCOUNT.ACCOUNT_ID AS ACCT_ID,
 PCDM.DW_DIM_DATE.DATE_ID AS DATE_ID,
 --PCDM.DW_DIM_MONTH.MONTH_ID AS MONTH_ID,
 PCDM.DW_DIM_POLICY.POLICY_ID AS ALT_PREMIUM_TRANSACTION_ID,
 NULL AS REC_TYPE_ID,
 DL_PC_EXT.V_POL_TRN_ALL_STG.ACCTG_PRD_ID AS ACCTG_PRD_ID,
 DL_PC_EXT.V_POL_TRN_ALL_STG.TRANSACTION_PRO_DATE AS TRANSACTION_PROC_DT_ID, 
 DL_PC_EXT.V_POL_TRN_ALL_STG.TRANS_EFF_DATE AS TRANSACTION_EFF_DT_ID, 
 DL_PC_EXT.V_POL_TRN_ALL_STG.TRANS_EXP_DATE AS TRANSACTION_EXP_DT_ID,
 DL_PC_EXT.V_POL_TRN_ALL_STG.TRANSACTION_PRO_DATE AS TRANSACTION_PROC_DATETIMESTAMP, 
NULL AS  RISK_TYPE_CD,
 'PC' AS SOURCE , 
 DL_PC_EXT.V_POL_TRN_ALL_STG.TRANSACTION_TYPE_CODE AS TRANSACTION_TYPE_CD, 
 DL_PC_EXT.V_POL_TRN_ALL_STG.TRANSACTION_CODE AS TRANSACTION_CD, 
 NULL AS TRANSACTION_SEQ,
 DL_PC_EXT.V_POL_TRN_ALL_STG.CURRENCY_CODE AS CURRENCY_CD,  
 DL_PC_EXT.V_POL_TRN_ALL_STG.TRANSACTION_AMOUNT AS TRANSACTION_AMOUNT,
 NULL AS TRANSACTION_ALLOC_CD,
 DL_PC_EXT.V_POL_TRN_ALL_STG.WRITTEN_PREMIUM_AMT AS WRITTEN_PREMIUM_AMOUNT, 
 DL_PC_EXT.V_POL_TRN_ALL_STG.INFORCE_PREM_AMOUNT AS INFORCE_PREMIUM_AMOUNT,
 DL_PC_EXT.V_POL_TRN_ALL_STG.TAX_AMOUNT AS TAX_AMOUNT,
 DL_PC_EXT.V_POL_TRN_ALL_STG.FEE_AMOUNT AS FEE_AMOUNT,
 DL_PC_EXT.V_POL_TRN_ALL_STG.SURCHARGE_AMOUNT AS SURCHARGE_AMOUNT,
 NULL AS COMMISSION_AMOUNT,
 NULL AS COMMISSION_PERCENT,
 DL_PC_EXT.V_POL_TRN_ALL_STG.PREM_FULLY_EARNED_FL AS PREMIUM_FULLY_EARNED_FLAG, 
 NULL AS ESTIMATED_PREMIUM_AMOUNT,
 NULL AS REPORTED_PREMIUM_AMOUNT,
 NULL AS AUDIT_PREMIUM_AMOUNT,
 DL_PC_EXT.V_POL_TRN_ALL_STG.PREM_BASIS_AMT AS PREMIUM_BASIS_AMOUNT,
 NULL AS AUDITABLE_FLAG,
 'Y' ETL_ACTIVE_FLAG,
 current_timestamp() AS ETL_ADD_DATETIMESTAMP,
 current_timestamp()  AS ETL_LAST_UPDATE_DATETIMESTAMP, 
 DL_PC_EXT.V_POL_TRN_ALL_STG.TOTALPREMIUMRPT AS TOTALPREMIUMRPT, 
 DL_PC_EXT.V_POL_TRN_ALL_STG.TOTALREPORTEDPREMIUM AS TOTALREPORTEDPREMIUM,
 NULL AS POLICY_STATUS_DESC_EXT
 from DL_PC_EXT.V_POL_TRN_ALL_STG
 LEFT OUTER JOIN PCDM.DW_DIM_ORGANIZATION
 ON DL_PC_EXT.V_POL_TRN_ALL_STG.ID = PCDM.DW_DIM_ORGANIZATION.ORG_ID
 LEFT OUTER JOIN PCDM.DW_DIM_PRODUCT
 ON DL_PC_EXT.V_POL_TRN_ALL_STG.ID = PCDM.DW_DIM_PRODUCT.PRODUCT_ID
 LEFT OUTER JOIN PCDM.DW_DIM_POLICY
 ON DL_PC_EXT.V_POL_TRN_ALL_STG.ID = PCDM.DW_DIM_POLICY.POLICY_ID
 LEFT OUTER JOIN PCDM.DW_DIM_LOCATION
 ON DL_PC_EXT.V_POL_TRN_ALL_STG.ID = PCDM.DW_DIM_LOCATION.LOCATION_ID
 LEFT OUTER JOIN PCDM.DW_DIM_AGENT
 ON DL_PC_EXT.V_POL_TRN_ALL_STG.ID = PCDM.DW_DIM_AGENT.AGENT_ID
 LEFT OUTER JOIN PCDM.DW_DIM_AGENCY
 ON DL_PC_EXT.V_POL_TRN_ALL_STG.ID = PCDM.DW_DIM_AGENCY.AGENCY_ID
 LEFT OUTER JOIN PCDM.DW_DIM_NAMED_INSURED
 ON DL_PC_EXT.V_POL_TRN_ALL_STG.ID = PCDM.DW_DIM_NAMED_INSURED.NAMED_INSURED_ID
 LEFT OUTER JOIN PCDM.DW_DIM_ACCOUNT
 ON DL_PC_EXT.V_POL_TRN_ALL_STG.ID = PCDM.DW_DIM_ACCOUNT.ACCOUNT_ID
 LEFT OUTER JOIN PCDM.DW_DIM_DATE 
 ON DL_PC_EXT.V_POL_TRN_ALL_STG.TRANS_EFF_DATE = PCDM.DW_DIM_DATE.DATE
 --LEFT OUTER JOIN PCDM.DW_DIM_MONTH 
 --ON  DL_PC_EXT.V_POL_TRN_ALL_STG.ACCTG_PRD_ID = PCDM.DW_DIM_MONTH.MMYYYY
 LEFT OUTER JOIN PCDM.DW_DIM_COVERAGE
 ON DL_PC_EXT.V_POL_TRN_ALL_STG.ID = PCDM.DW_DIM_COVERAGE.COVERAGE_ID
 ORDER BY DL_PC_EXT.V_POL_TRN_ALL_STG.ID ;